### ISSUE TITLE
support for a go-gettable module name

### ISSUE THREAD

**Issue by torbenschinke** [jakecoffman/cp-examples#5]
Currently one can not use go install/run with the examples, because the module name in go.mod does not match the import path:

```bash
go run github.com/jakecoffman/cp-examples/player@latest 
go: github.com/jakecoffman/cp-examples/player@latest: github.com/jakecoffman/cp-examples@v0.0.0-20220706021553-d9cc2516e648: parsing go.mod:
	module declares its path as: cp-examples
	        but was required as: github.com/jakecoffman/cp-examples
```

Probably, the go.mod should contain `github.com/jakecoffman/cp-examples` instead of `cp-examples`.

**Comment by jakecoffman** [comment]
Fixed! Thanks for letting me know it was broken.
